export { default as HiddenLabel } from "./hidden-label/hidden-label";
export { default as HiddenSpan } from "./hidden-span/hidden-span";
export { default as P } from "./p/p";
export { default as Button } from "./button/button";
export { default as MainTitle } from "./text/main-title/main-title";
export { default as ContentWrapper } from "./content-wrapper/content-wrapper";
export { default as Ul } from "./ul/ul";
export { default as Li } from "./li/li";
export { default as IconButton } from "./icon-button/icon-button";
